Angry_Mustache_Man

medium

# Not checking the return value of withdraw function can cause DOS

## Summary
In `AaveV3LeverageModule.sol::delever` when the `withdraw` function is called, it goes on to call `invokeWithdraw` function. The `invokewithdraw` function returns the actual amount withdrawn from Aave which is never used . This might cause DOS.
## Vulnerability Detail
The mechanism goes as `AaveV3LeverageModule:delever->AaveV3LeverageModule:withdraw->AaveV3:invokeWithdraw`. In invokewithdraw the function calls Pool.withdraw and gets a return value, which is the actual amount withdrawn . According to Aave docs and Repo : (actual amount withdrawn) <=(amount mentioned[amt]). But the problem occurs when in the next step of delever function the `executetrade` is called by the outdated `notionalSendQuantity(which is amt as above)`. So when the actual withdrawn amount is less than `amt` , `executetrade` will revert and would cause an unexpected DOS.
## Impact
Can cause unexpected DOS .
## Code Snippet
https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/modules/v1/AaveV3LeverageModule.sol#L755-#L757
## Tool used

Manual Review

## Recommendation

Use the return value of `invokeWithdraw` in `executetrade` function and not outdated `notionalSendQuantity`